# This file is part of django-unused-media.
# https://github.com/akolpakov/django-unused-media

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2015, Andrey Kolpakov <aakolpakov@gmail.com>

language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "pypy"

install:
    - make setup

script:
    - make flake8
    - make test

addons:
    apt_packages:
        - pandoc
